RHTAP-2994 Jenkins tests for GitHub
redhat-appstudio/rhtap-e2e pull request #141
Opened 2024-08-29 09:09 UTC by jkopriva

2024-08-29 09:09 UTC, jkopriva commented
/test all

2024-08-29 09:23 UTC, jkopriva commented
/test all

2024-09-02 17:24 UTC, flacatus commented
I really like the solution. We are setting up the new infra for rhtap e2e. Once is ready we can merge it!

Question:

Do we really need for every language?

2024-09-03 04:51 UTC, jkopriva commented
@flacatus Thank you! Right now the Jenkins stuff is disabled. I have another commit for GitLab ready, just waiting for this one to be merged.
Ad languages: I am thinking, what if we in next PR(s) rework tests to have some smoke suite? You can run half of the languages for GitHub and the other half on GitLab? You will still need to run all tests for release testing, but CI on PRs could run only smoke and weekly job will also run full suite? WDYT?

2024-09-03 09:41 UTC, prietyc123 requested changes

2024-09-04 12:43 UTC, jkopriva commented on src/apis/git-providers/github.ts
> +    public async createAgentCommit(gitOrg: string, gitRepository: string): Promise<string | undefined> {
Done, resolving

2024-09-04 12:44 UTC, jkopriva commented on src/apis/ci/jenkins.ts
> +    // Function to trigger a build for a Jenkins job
Fixed, resolving

2024-09-04 12:47 UTC, jkopriva commented on jest.config.js
> +                templates:  ['dotnet-basic', 'go', 'nodejs', 'python', 'java-quarkus', 'java-springboot'],
Fixed, resolving!

2024-09-04 12:48 UTC, jkopriva commented
@prietyc123 Thank you for review and testing!

2024-09-05 06:53 UTC, flacatus commented
/lgtm

2024-09-10 07:38 UTC, flacatus commented
/lgtm

2024-09-10 07:45 UTC, flacatus approved these changes

2024-09-10 07:45 UTC, merged