RHTAP-3027 Jenkins/Github advanced test with promotion pipeline
redhat-appstudio/rhtap-e2e pull request #162
Opened 2024-09-24 08:10 UTC by jkopriva

2024-10-09 11:50 UTC, jkopriva commented
/retest

2024-10-11 10:24 UTC, jkopriva commented
/retest

2024-10-14 15:58 UTC, jkopriva commented
/retest

2024-11-15 13:16 UTC, rhopp requested changes

2024-12-02 13:24 UTC, jkopriva commented on tests/gpts/github/test-config/github_advanced_jenkins.ts
> +        it('trigger pull request promotion to promote from stage to prod environment', async () => {
Fixed

2024-12-02 13:24 UTC, jkopriva commented on tests/gpts/github/test-config/github_advanced_jenkins.ts
> +        it(`Trigger job and wait for ${gptTemplate} jenkins job to finish`, async () => {
Fixed

2024-12-02 13:25 UTC, jkopriva commented on tests/gpts/github/test-config/github_advanced_jenkins.ts
> +        it(`Trigger job and wait for ${gptTemplate} jenkins job to finish`, async () => {
Fixed

2024-12-02 13:25 UTC, jkopriva commented on tests/gpts/github/test-config/github_advanced_jenkins.ts
> +        it(`merge gitops pull request to sync new image in stage environment`, async () => {
Fixed

2024-12-02 13:25 UTC, jkopriva commented on tests/gpts/github/test-config/github_advanced_jenkins.ts
> +        it('container component is successfully synced by gitops in prod environment', async () => {
Fixed

2024-12-02 13:33 UTC, jkopriva commented
@rhopp Can you please review once again?
![image](https://github.com/user-attachments/assets/3c102e03-16ba-4f8f-be37-c879eb25af15)

2024-12-03 16:06 UTC, rhopp reviewed
Read through the PR... Found few minor issues (not directly blocking the PR). 
I would like to run the tests tomorrow though ;-)

2024-12-03 16:06 UTC, rhopp commented on src/apis/git-providers/github.ts
> +        public async updateTUFMirror(gitOrg: string, gitRepository: string, tufURL: string): Promise<string | undefined> {
Indentation is off

2024-12-03 16:06 UTC, rhopp commented on src/apis/git-providers/github.ts
> +                public async updateRekorHost(gitOrg: string, gitRepository: string, rekorHost: string): Promise<string | undefined> {
Intentation is off

2024-12-04 06:53 UTC, jkopriva commented on src/apis/git-providers/github.ts
> +        public async updateTUFMirror(gitOrg: string, gitRepository: string, tufURL: string): Promise<string | undefined> {
fixed, thanks!

2024-12-04 06:53 UTC, jkopriva commented on src/apis/git-providers/github.ts
> +                public async updateRekorHost(gitOrg: string, gitRepository: string, rekorHost: string): Promise<string | undefined> {
fixed, thanks!

2024-12-04 07:01 UTC, jkopriva commented on src/apis/git-providers/github.ts
> +     * @returns {Promise<string | undefined>} A Promise resolving to the SHA of the commit if successful, otherwise undefined.
fixed. thanks!

2024-12-04 12:11 UTC, jkopriva commented
/retest

2024-12-04 14:22 UTC, rhopp approved these changes

2024-12-04 16:13 UTC, merged